from distutils.core import setup

setup(
    name = 'summa-visualization',
    packages = ['visualization'],
    package_data = {
        'visualization': ['README', 'LICENSE']
    },
    version = '0.1.0',
    description = 'A visualization for the graphs generated by summa.',
    author = 'Federico Barrios, Federico Lopez',
    author_email = 'summanlp@gmail.com',
    url = 'https://github.com/summanlp/summa-visualization',
    download_url = 'https://github.com/summanlp/summa-visualization/tarball/v0.1.0',
    keywords = ['summa', 'nlp', 'summarization', "NLP", "natural language processing", "automatic summarization",
        "keywords", "summary", "textrank", "pagerank"],
    classifiers = [
        # How mature is this project? Common values are
        #   3 - Alpha
        #   4 - Beta
        #   5 - Production/Stable
        'Development Status :: 4 - Beta',

        'License :: OSI Approved :: MIT License',

        'Intended Audience :: Developers',
        'Intended Audience :: Education',

        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Text Processing :: Linguistic',

        # Specify the Python versions you support here. In particular, ensure
        # that you indicate whether you support Python 2, Python 3 or both.
        'Programming Language :: Python :: 2.7'
    ],
    long_description = open('README').read()
)